language: node_js
node_js:
  - 10
sudo: required
install:
  - npm install
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - npm run build
  - npm run deploy:travis
deploy:
  - provider: npm
    email: $EMAIL_ADDRESS
    api_key: $NPM_API
    skip_cleanup: true
    on:
      tags: true